### ISSUE TITLE
Interferes with Social Plugin

### ISSUE THREAD

**Issue by Westlake56** [twentyfiveautumn/twitter_bootstrap#34]
I'm running 1.9.8. I have the Social Login plugin by Gerard Kanters and the quick registration prevents it from showing the logins. I currently have Facebook, Google, Twitter and Linkedin, none of them show below the quick registration like the regular registration does.

Not being a developer / programmer, I have no idea if there is a way for you to have it get along with the social login. That is the one problem sometimes with plugins.

Dan

**Comment by twentyfiveautumn** [comment]
I'll try and get a look at this in the next few days and get back with you. Thanks

**Comment by Westlake56** [comment]
That would be great.

On 2/25/15 6:41 AM, Ray wrote:
>
> I'll try and get a look at this in the next few days and get back with 
> you. Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/twentyfiveautumn/twitter_bootstrap/issues/34#issuecomment-75946731>.
>

-- 

BITS Of Knowledge
796 Dundalk Dr.
London, ON N6C 3V2

519-681-2555

http://www.bitsofknowledge.com

Everything For Seniors Directory - Phone: 519-681-2555
http://everythingforseniorsdirectory.ca 
<http://everythingforseniorsdirectory.ca/>

CONFIDENTIALITY NOTICE: This email including any attachments may contain 
confidential or proprietary information. All information contained 
herein is for the exclusive and confidential use of the intended 
recipient. If you are not the intended recipient, please do not read, 
distribute or take action in reliance upon this message. Any 
distribution, copying, use, disclosure or dissemination of this 
information is unauthorized, strictly prohibited, and may be illegal. If 
you have received this message in error, please notify the sender 
immediately and promptly destroy this message and its attachments 
including any copies.

**Comment by twentyfiveautumn** [comment]
If you go to http://YOUR_WEBSITE/login does it work?

**Comment by Westlake56** [comment]
Yes it does. There is one small display problem, that is the full word for password doesn't display. I tried zooming in and out with Firefox, Internet Explorer and Chrome, all of them just show Passw.
![twitter-bootstrap](https://cloud.githubusercontent.com/assets/11148775/6391984/fccdfe40-bd89-11e4-835a-f4d60ba15c87.png)

**Comment by Westlake56** [comment]
I didn't read it correctly, I could not login with the user id or password. I had to use the login with the twitter bootstrap plugin login.

**Comment by twentyfiveautumn** [comment]
We're not really able to change the form because it's also used on the login page.
See http://twentyfiveautumn.com/login
You might try copying the file:
**elgg/views/default/forms/login.php**
to
**elgg/mod/twitter_bootstrap/views/default/forms/login.php**

and see if that works for you.

**Comment by Westlake56** [comment]
That worked. I was also able to register as a new user.
