### ISSUE TITLE
CKEditor doesn't work

### ISSUE THREAD

**Issue by CircusMusic** [twentyfiveautumn/twitter_bootstrap#41]
Plugin blows away the classes in *twitter_bootstrap/views/default/input/longtext.php* which removes the classes needed for the CKEditor to function on the text areas.

Fixed by changing line 20 from:
```php
$vars['class'] = "col-md-12";
```
to:
```php
$vars['class'] .= " col-md-12";
```

**Comment by twentyfiveautumn** [comment]
What plugin was causing the issue? Thanks for reporting.

**Comment by CircusMusic** [comment]
I guess I meant to say theme..  I made the change directly in the code for this theme

**Comment by twentyfiveautumn** [comment]
Are you saying you CKEditor will not load or ?
 https://community.elgg.org/plugins/1894726 is best because the master here is a work in progress and can be buggy at times

**Comment by CircusMusic** [comment]
Yea, it wont load.
Like I said on line 20 of *twitter_bootstrap/views/default/input/longtext.php* you have it overwriting $vars['class'] so it ends up not having the "elgg-input-longtext" class, just the "col-md-12" class only.

This is from the zip files I downloaded from https://community.elgg.org/plugins/1894726 (for both version of elgg)

**Comment by twentyfiveautumn** [comment]
Thanks @CircusMusic 
I'll look into this. I had it commented out on localhost and that was working but funny because it works on http://twentyfiveautumn.com and it's not commented out over there. Is it effecting every longtext ?
You would think it would.

**Comment by CircusMusic** [comment]
Just started looking at elgg today actually so I don't have a lot of experience with the code structure, etc..
It seems to effect all of them for my installation.  When I apply the fix from my first post all text areas have CKEditor loaded.
Maybe it's due to the load order of the plugins?  I have this theme loaded last.

**Comment by twentyfiveautumn** [comment]
You do want the theme loaded last. Thanks for your help.
We'll get this fixed for the next release

**Comment by twentyfiveautumn** [comment]
now passes in 'col-md-12' as a variable as it should work. It was only used in two places.
We no longer need to over ride the core input/longtext file.
Closing this. Please feel free to report any other issues you come across & thanks for pointing this out.
